#!/bin/bash
set -ex

sqlite3 << 'END_SQL'
.mode csv
.separator ,
.import categorized_trackers.csv trackers
CREATE UNIQUE INDEX domain_idx ON trackers(domain);
-- Instructions to modify the table here
.read "category_patches/002 - TR Update Nov 2024.sql"
-- END modification - now export
.output categorized_trackers.csv
.headers on
SELECT * FROM trackers ORDER BY domain ASC;
.output stdout
END_SQL

# Remove double quotes generated by the sqlite export
sed -i 's/""//g' categorized_trackers.csv